### ISSUE TITLE
Support on OS

### ISSUE THREAD

**Issue by mingwayzhang** [airbus-seclab/ramooflax#2]
Dear Stephane Duverger,

Thanks for sharing the work. I recently try to setup the ramooflax by myself. Before that, I am wondering which type of OSs are currently supported (for instance, Linux kernel version?)? I read some of your slides which are pretty old, but I do see some updates committed recently. So, appreciate it if you could let me know. Thanks.

-Mingwei

**Comment by sduverger** [comment]
Hello,

Yes, sorry the slides are pretty old. As well as the documentation. But the code is updated regularly.
Actually, any OS is supported and "should" work. Intel CPU are now required, since AMD port is not updated for a long time.

If you intend to run a Linux kernel, you should not have any trouble whether it is 32 or 64 bits.
The better choice for trying Ramooflax is using VMWare Workstation. So that you have a fixed known and working hardware. You can install a Linux distrubition inside a VMWare VM and after that install ramooflax binaries in a new Grub entry of your VM.

Do not forget to enable Nested Virtualization inside the VM preferences, so that ramooflax can use make of use Intel VTX/EPT inside the VMWare VM.

You may compile ramooflax with a serial port device for logging (and get resultats inside a file under vmware) and a network E1000 interface as controlling device. Again, do not miss your VM configuration to make sure one of the VNET is of type E1000 for ramooflax usage.

If you have trouble, let me know. I'll try to help you as much as i can.

If you want to try out ramooflax on real hardware, you may experience trouble with your BIOS. Sometimes it works flawlessly, sometime it won't :)

May i know why are you trying ramooflax ? Just for my curiosity.
